"use client";
import {useEffect,useState} from "react";
import PhotoInput from "./PhotoInput";
type Row=Record<string,any>;
type Api=(path:string,method?:string,body?:any)=>Promise<any>;
const names:Row={conditions:"定理条件",quantifiers:"量词与依赖",construction:"辅助构造",confirmed:"确认问题",rejected:"无此问题",ignored:"暂不判断",independent_success:"独立完成",accepted:"已采纳",pending:"待处理",candidate:"待确认"};
export default function AssignmentPages({api,user,courses,view="assignments",demonstration=false}:{api:Api;user:Row;courses:Row[];view?:string;demonstration?:boolean}){
 const teacher=user.role==="teacher"||user.role==="ta";
 const [boxes,setBoxes]=useState<Row[]>([]),[sid,setSid]=useState(""),[works,setWorks]=useState<Row[]>([]),[findings,setFindings]=useState<Row[]>([]),[report,setReport]=useState<Row|null>(null);
 const [workId,setWorkId]=useState(""),[create,setCreate]=useState(false),[submitId,setSubmitId]=useState(""),[draft,setDraft]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[edit,setEdit]=useState("");
 const [hours,setHours]=useState(3),[record,setRecord]=useState(false);
 useEffect(()=>{api("/config").then(c=>setHours(c.default_retention_hours)).catch(()=>{});void load();},[]);
 async function load(){try{const rows=await api("/sandboxes");setBoxes(rows);setSid(current=>current||new URLSearchParams(window.location.search).get("assignment")||rows[0]?.id||"");}catch(e){setError(String((e as Error).message));}}
 useEffect(()=>{void detail();},[sid,view]);
 async function detail(){
  if(!sid||view==="assignments")return;
  try{if(view==="review"){const [w,f]=await Promise.all([api("/sandboxes/"+sid+"/submissions"),api("/sandboxes/"+sid+"/findings")]);setWorks(w);setFindings(f);setWorkId(current=>w.some((x:Row)=>x.id===current)?current:w[0]?.id||"");}else setReport(await api("/sandboxes/"+sid+"/report"));}catch(e){setError((e as Error).message);}
 }
 async function run(task:()=>Promise<void>){if(busy)return;setBusy(true);setError("");setNotice("");try{await task();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const box=boxes.find(b=>b.id===sid),work=works.find(w=>w.id===workId);
 const link=(page:string,id:string)=>"/teacher/"+page+"?assignment="+id+(demonstration?"&mode=demo":"&mode=live");
 function download(){const url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:"application/json"}));const a=document.createElement("a");a.href=url;a.download="作业报告.json";a.click();URL.revokeObjectURL(url);}
 return <section className="assignmentsPage"><div className="pageHeading"><h1>{view==="review"?"作品批改":view==="reports"?"教学报告":teacher?"作业管理":"我的作业"}</h1>{view==="assignments"&&user.role==="teacher"&&<button className="primary" onClick={()=>setCreate(!create)}>布置作业</button>}</div>
 {error&&<p className="portalError" role="alert">{error}</p>}{notice&&<p className="saveNotice" role="status">{notice}</p>}
 {view==="assignments"?<>
 {!teacher&&<form className="joinAssignment" onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);void run(async()=>{await api("/sandboxes/join","POST",{code:form.get("code")});await load();setNotice("已加入");});}}><label>作业码<input name="code" required/></label><button disabled={busy}>加入作业</button></form>}
 {create&&<form className="pilotCard pilotForm formGrid" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(async()=>{await api("/sandboxes","POST",{course_id:f.get("course"),title:f.get("title"),class_label:f.get("class"),class_size:Number(f.get("size"))||null,assignment:f.get("assignment"),retention_hours:Number(f.get("hours")),retention_confirmed:true});setCreate(false);await load();setNotice("已发布");});}}>
 <label>课程<select name="course">{courses.map(c=><option key={c.course_id} value={c.course_id}>{c.display_name}</option>)}</select></label><label>作业名称<input required name="title"/></label><label>班级<input name="class"/></label><label>班级人数<input type="number" min="1" name="size"/></label><label className="wideField">作业要求<textarea name="assignment" rows={4}/></label><label>资料保留时长（小时）<input required type="number" min="1" max="720" name="hours" defaultValue={hours}/></label><label className="check"><input type="checkbox" required/>确认到期清理作业资料</label><div><button className="primary" disabled={busy}>发布</button><button type="button" onClick={()=>setCreate(false)}>取消</button></div></form>}
 <div className="assignmentCards">{boxes.map(b=><article className="pilotCard" key={b.id}><div className="panelHeading"><h2>{b.title}</h2><span className={"statusTag "+(b.status==="open"?"ready":"closed")}>{b.status==="open"?"进行中":"已结束"}</span></div><p>{b.assignment}</p><p>截止：{new Date(b.expires_at).toLocaleString("zh-CN")}</p>
 {teacher?<><p>作业码：{b.join_code||"—"}</p><div className="pilotActions"><a className="actionLink" href={link("review",b.id)}>批改</a><a className="actionLink" href={link("reports",b.id)}>报告</a>{b.owner&&<button onClick={()=>setEdit(edit===b.id?"":b.id)}>管理</button>}</div>
 {edit===b.id&&b.owner&&<div className="assignmentManage">
 {b.status==="open"&&<><form className="inlineForm" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(async()=>{await api("/sandboxes/"+b.id+"/retention","PATCH",{retention_hours:Number(f.get("hours")),confirmed:true});await load();setNotice("已更新");});}}><label>资料保留时长（小时）<input type="number" min="1" max="720" name="hours" defaultValue={b.retention_hours}/></label><button disabled={busy}>保存期限</button></form><form className="inlineForm" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(async()=>{await api("/sandboxes/"+b.id+"/ta","POST",{username:f.get("username")});setNotice("已添加助教");});}}><label>助教账号<input required name="username"/></label><button disabled={busy}>添加助教</button></form>
 <button disabled={busy} onClick={()=>{if(confirm("结束后将停止提交和批改，是否继续？"))void run(async()=>{await api("/sandboxes/"+b.id+"/close","POST");await load();});}}>结束作业</button></>}
 <button disabled={busy||b.purged} onClick={()=>{if(confirm("删除此作业的作品和成员记录？已保存的汇总报告保留。"))void run(async()=>{await api("/sandboxes/"+b.id,"DELETE");await load();});}}>删除作业资料</button></div>}</>
 :b.status==="open"&&!b.purged&&<><button onClick={()=>{setSubmitId(submitId===b.id?"":b.id);setDraft("");}}>提交作业</button>{submitId===b.id&&<form className="pilotForm" onSubmit={e=>{e.preventDefault();void run(async()=>{await api("/sandboxes/"+b.id+"/submissions","POST",{text:draft,source:"artifact",synthetic:demonstration,explicit_submission:true});setSubmitId("");setNotice("已提交");});}}><PhotoInput disabled={busy} recognize={data=>api("/recognize","POST",{data_url:data})} onText={setDraft}/><label>作答内容<textarea rows={6} required value={draft} onChange={e=>setDraft(e.target.value)}/></label><label className="check"><input required type="checkbox"/>将此内容提交给教师</label><button className="primary" disabled={busy}>确认提交</button></form>}</>}
 </article>)}</div>{!boxes.length&&<p>暂无作业</p>}
 </>:<><label className="assignmentSelect">作业<select value={sid} onChange={e=>{setSid(e.target.value);setReport(null);setWorks([]);}}>{boxes.map(b=><option key={b.id} value={b.id}>{b.title}</option>)}</select></label>
 {view==="review"?<>{box?.status==="open"&&<div className="pilotActions"><button onClick={()=>setRecord(!record)}>录入作品</button></div>}
 {record&&<form className="pilotCard pilotForm" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(async()=>{await api("/sandboxes/"+sid+"/submissions","POST",{participant_username:f.get("student"),source:f.get("source"),text:f.get("text"),synthetic:demonstration,explicit_submission:true});await detail();setRecord(false);setNotice("已录入");});}}><label>学生账号<input name="student" required/></label><label>作品类型<select name="source"><option value="artifact">作业作品</option><option value="independent">独立测试</option></select></label><label>作答内容<textarea name="text" required rows={5}/></label><label className="check"><input type="checkbox" required/>确认学生已提交此作品用于教学评价</label><button disabled={busy}>保存作品</button></form>}
 <div className="reviewLayout"><aside className="pilotCard workList"><h2>提交列表</h2>{works.map(w=><button key={w.id} aria-current={workId===w.id?"true":undefined} onClick={()=>setWorkId(w.id)}>{w.participant}<span>{w.review.decision?"已批改":"待批改"}</span></button>)}{!works.length&&<p>暂无提交</p>}</aside>
 {work&&<article className="pilotCard selectedWork"><h2>{work.participant}</h2><p className="workText">{work.text}</p>
 {work.review.candidate&&<section className="reviewSuggestion"><h3>批改参考</h3><p>{work.review.candidate.text}</p></section>}
 {work.review.note&&<p>批注：{work.review.note}</p>}
 {box?.status==="open"&&<><button disabled={busy} onClick={()=>run(async()=>{await api("/submissions/"+work.id+"/preanalysis","POST");await detail();})}>辅助批改</button>
 <form className="pilotForm" key={work.id} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(async()=>{await api("/submissions/"+work.id+"/review","POST",{theme:f.get("theme"),decision:f.get("decision"),note:f.get("note")});await detail();setNotice("已保存批改");});}}>
 <label>主题<select name="theme">{["conditions","quantifiers","construction"].map(t=><option key={t} value={t}>{names[t]}</option>)}</select></label><label>判断<select name="decision"><option value="confirmed">确认问题</option><option value="rejected">无此问题</option><option value="ignored">暂不判断</option>{work.source==="independent"&&<option value="independent_success">独立完成</option>}</select></label><label>批注<textarea required name="note" rows={3} defaultValue={work.review.note||""}/></label><button className="primary" disabled={busy}>保存批改</button></form></>}
 </article>}</div>
 <section className="pilotCard"><div className="panelHeading"><h2>班级问题</h2><button disabled={busy||!sid||box?.status!=="open"} onClick={()=>run(async()=>{setFindings(await api("/sandboxes/"+sid+"/insights","POST"));})}>汇总问题</button></div>
 {findings.map(f=><article className="findingRow" key={f.finding_id}><p>{f.phenomenon}</p><span>{names[f.teacher_status==="accepted"?"accepted":f.ta_status]||"待处理"}</span>{box?.status==="open"&&f.teacher_status==="pending"&&<div className="pilotActions">{["confirmed","ignored"].map(d=><button key={d} disabled={busy} onClick={()=>run(async()=>{await api("/findings/"+f.finding_id+"/decision","POST",{stage:"ta",decision:d,note:""});await detail();})}>{d==="confirmed"?"确认":"忽略"}</button>)}{box?.owner&&f.ta_status==="confirmed"&&<button disabled={busy} onClick={()=>run(async()=>{await api("/findings/"+f.finding_id+"/decision","POST",{stage:"teacher",decision:"accepted",note:""});await detail();})}>纳入报告</button>}</div>}</article>)}</section>
 </>:report&&<section className="pilotCard"><div className="panelHeading"><h2>{report.title}</h2><button onClick={download}>导出报告</button></div>
 <div className="metrics">{[[report.participants,"学习参与"],[report.artifact_participants,"作品提交"],[report.independent_participants,"独立表现"],[report.confirmed_issues,"确认问题"]].map(([n,t])=><div key={t}><strong>{n}</strong><span>{t}</span></div>)}</div>
 <h2>已确认问题</h2>{report.findings?.length?report.findings.map((f:Row)=><p key={f.finding_id}>{f.phenomenon}</p>):<p>暂无确认问题</p>}
 {!!report.teaching_actions?.length&&<><h2>教学建议</h2>{report.teaching_actions.map((a:Row)=><p key={a.theme}>{a.suggestion}</p>)}</>}
 </section>}</>}
 </section>;
}
