export type Material={resource_id:string;course_id:string;kind:"textbook"|"exam";title:string;authors:string[];edition:string|null;volume:string|null;publication_year:number|null;exam_year:number|null;tags:string[];cover_url:string|null;pdf_url:string|null;page_count:number|null;completeness:"unverified"|"partial"|"complete";availability:"ready"|"pending"|"restricted";role:"primary"|"supplementary"|"unassigned"};
export type LibraryFilter={q:string;course_id:string;kind:"textbook"|"exam";year:string;tag:string;page:number};
export type LibraryPage={items:Material[];total:number;page:number;page_size:number};
export const pageSize=12;
export function readLibraryFilter():LibraryFilter {const p=new URLSearchParams(window.location.search);return {q:p.get('q')||'',course_id:p.get('course_id')||'',kind:p.get('kind')==='exam'?'exam':'textbook',year:p.get('year')||'',tag:p.get('tag')||'',page:Math.max(1,Number.parseInt(p.get('page')||'1',10)||1)};}
export function libraryQuery(f:LibraryFilter){const p=new URLSearchParams();for(const k of ['q','course_id','kind','year','tag'] as const)if(f[k])p.set(k,f[k]);p.set('page',String(f.page));p.set('page_size',String(pageSize));return p;}
export function syncLibraryLocation(f:LibraryFilter){const url=new URL(window.location.href);for(const k of ['q','course_id','kind','year','tag','page','page_size'])url.searchParams.delete(k);libraryQuery(f).forEach((v,k)=>url.searchParams.set(k,v));window.history.pushState(null,'',url);}
export class LibraryError extends Error {constructor(public status:number,message:string){super(message);}}
export function libraryError(status:number){return status===401?'登录已过期，请重新登录后查看资料。':status===403?'当前账号无权访问这份资料。':status===404?'资料不存在或当前账号不可见。':status===409?'原件尚未就绪，请稍后重试。':'资料服务暂不可用，请重试。';}
// Only canonical same-origin authenticated endpoints may become media URLs.
export function materialAsset(item:Material,type:'pdf'|'cover'):string|null {const raw=type==='pdf'?item.pdf_url:item.cover_url;if(!raw)return null;try{const u=new URL(raw,window.location.origin),expected='/api/v2/material-library/'+encodeURIComponent(item.resource_id)+'/'+type;if(u.origin!==window.location.origin||u.pathname!==expected||u.search||u.hash||u.username||u.password)return null;return u.pathname;}catch{return null;}}
export async function fetchLibrary(f:LibraryFilter,signal:AbortSignal):Promise<LibraryPage>{const r=await fetch('/api/v2/material-library?'+libraryQuery(f),{credentials:'include',cache:'no-store',signal});if(!r.ok)throw new LibraryError(r.status,libraryError(r.status));const data=await r.json();if(!Array.isArray(data.items)||!Number.isSafeInteger(data.total)||data.total<0||!Number.isSafeInteger(data.page)||data.page<1||!Number.isSafeInteger(data.page_size)||data.page_size<1||data.page_size>50)throw new Error('目录响应格式无效，请重试。');return data;}
export async function checkPdf(url:string,signal:AbortSignal){const r=await fetch(url,{credentials:'include',cache:'no-store',headers:{Range:'bytes=0-4'},signal});if(!r.ok)throw new LibraryError(r.status,libraryError(r.status));if(!r.headers.get('content-type')?.toLowerCase().includes('application/pdf')){await r.body?.cancel();throw new Error('服务返回的文件不是 PDF，暂不能阅读。');}const reader=r.body?.getReader();if(!reader)throw new Error('PDF 内容为空。');let prefix='';try{while(prefix.length<5){const {done,value}=await reader.read();if(done)break;prefix+=new TextDecoder('ascii').decode(value.slice(0,5-prefix.length));}}finally{await reader.cancel().catch(()=>{});}if(prefix!=='%PDF-')throw new Error('PDF 文件头无效，可能是损坏文件或下载占位，请联系管理员。');}
