"use client";
import {useEffect,useRef,useState} from 'react';
import StudentIcon from './StudentIcon';
import {Material,LibraryFilter,LibraryPage,LibraryError,readLibraryFilter,libraryQuery,syncLibraryLocation,fetchLibrary,materialAsset,checkPdf} from './material-library';
import './student-material-library.css';
type Row=Record<string,any>;
function Cover({item}:{item:Material}){const [failed,setFailed]=useState(false),url=materialAsset(item,'cover');return <div className="mlCover">{url&&!failed?<img src={url} alt={item.title+' 封面'} loading="lazy" onError={()=>setFailed(true)}/>:<div className="mlCoverMissing"><StudentIcon name="library"/><span>暂无可用封面</span></div>}</div>;}
export default function ResourceCenter({courses}:{api:(path:string,method?:string,body?:unknown)=>Promise<any>;courses:Row[]}){
 const [filter,setFilter]=useState<LibraryFilter|null>(null),[draft,setDraft]=useState({q:'',tag:'',year:''});
 const [data,setData]=useState<LibraryPage|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[status,setStatus]=useState(0),[retry,setRetry]=useState(0);
 const [selected,setSelected]=useState<Material|null>(null),[pdf,setPdf]=useState(''),[pdfLoading,setPdfLoading]=useState(false),[pdfError,setPdfError]=useState(''),[pdfStatus,setPdfStatus]=useState(0);
 const listAbort=useRef<AbortController|null>(null),pdfAbort=useRef<AbortController|null>(null),listEpoch=useRef(0),pdfEpoch=useRef(0),listScroll=useRef(0),heading=useRef<HTMLHeadingElement>(null);
 useEffect(()=>{const restore=()=>{listEpoch.current++;listAbort.current?.abort();closePdf();setRetry(n=>n+1);const f=readLibraryFilter();setFilter(f);setDraft({q:f.q,tag:f.tag,year:f.year});};restore();window.addEventListener('popstate',restore);return()=>{window.removeEventListener('popstate',restore);listEpoch.current++;pdfEpoch.current++;listAbort.current?.abort();pdfAbort.current?.abort();};},[]);
 const key=filter?libraryQuery(filter).toString():'';
 useEffect(()=>{if(!filter)return;const epoch=++listEpoch.current,controller=new AbortController();listAbort.current?.abort();listAbort.current=controller;setLoading(true);setError('');setStatus(0);setData(null);fetchLibrary(filter,controller.signal).then(value=>{if(epoch===listEpoch.current)setData(value);}).catch(e=>{if(!controller.signal.aborted&&epoch===listEpoch.current){setError(e.message);setStatus(e instanceof LibraryError?e.status:0);}}).finally(()=>{if(epoch===listEpoch.current)setLoading(false);});return()=>controller.abort();},[key,retry]);
 function closePdf(){pdfEpoch.current++;pdfAbort.current?.abort();setSelected(null);setPdf('');setPdfError('');setPdfLoading(false);setPdfStatus(0);}
 function change(next:LibraryFilter){listEpoch.current++;listAbort.current?.abort();closePdf();setFilter(next);setDraft({q:next.q,tag:next.tag,year:next.year});syncLibraryLocation(next);if(filter&&libraryQuery(next).toString()===key)setRetry(n=>n+1);}
 async function openPdf(item:Material){const epoch=++pdfEpoch.current;pdfAbort.current?.abort();const controller=new AbortController();pdfAbort.current=controller;if(!selected)listScroll.current=window.scrollY;setSelected(item);setPdf('');setPdfError('');setPdfStatus(0);setPdfLoading(true);heading.current?.focus();const url=materialAsset(item,'pdf');try{if(item.availability!=='ready')throw new Error(item.availability==='restricted'?'当前资料访问受限。':'原件尚未就绪。');if(!url)throw new Error('尚无可用的授权 PDF 地址。');await checkPdf(url,controller.signal);if(epoch===pdfEpoch.current)setPdf(url);}catch(e){if(epoch===pdfEpoch.current&&!controller.signal.aborted){setPdfError((e as Error).message);setPdfStatus(e instanceof LibraryError?e.status:0);}}finally{if(epoch===pdfEpoch.current)setPdfLoading(false);}}
 function back(){closePdf();requestAnimationFrame(()=>window.scrollTo(0,listScroll.current));}
 if(!filter)return <p role="status">正在准备资源目录…</p>;
 return <section className="lmMaterialLibrary">
  <header className="mlHeading"><h1 ref={heading} tabIndex={-1}>资源中心</h1><p>按书名、作者、ISBN 或标签查找资料，阅读原版 PDF。</p></header>
  {selected?<section className="mlReader" aria-label="PDF 阅读区"><div className="mlReaderHead"><button onClick={back}>← 返回目录</button><h2>{selected.title}</h2>{selected.edition&&<span>{selected.edition}</span>}</div>
   {pdfLoading&&<p role="status">正在检查 PDF 访问权限…</p>}
   {pdfError&&<div role="alert" className="mlError">{pdfError}{pdfStatus===401?<a href="/login">重新登录</a>:<button onClick={()=>void openPdf(selected)}>重试 PDF</button>}</div>}
   {pdf&&<><div className="mlReaderActions"><a href={pdf} target="_blank" rel="noopener noreferrer">打开 PDF <StudentIcon name="arrow"/></a><button onClick={()=>void openPdf(selected)}>重新检查访问</button></div><p className="mlHint">如浏览器无法内嵌阅读，请使用“打开 PDF”。可用浏览器内置查找；有原件不代表教材内容已审校。</p><object key={pdf} data={pdf} type="application/pdf" aria-label={selected.title+' 原版PDF'}><p>此浏览器无法内嵌 PDF。<a href={pdf} target="_blank" rel="noopener noreferrer">打开 PDF 阅读</a></p></object></>}
  </section>:<>
  <form className="mlSearch" onSubmit={e=>{e.preventDefault();change({...filter,...draft,q:draft.q.trim(),tag:draft.tag.trim(),page:1});}}><div className="mlSearchInput"><StudentIcon name="search"/><input aria-label="搜索教材" placeholder="搜索书名、作者、ISBN 或标签" value={draft.q} maxLength={300} onChange={e=>setDraft({...draft,q:e.target.value})}/></div><button className="mlPrimary" type="submit"><StudentIcon name="search"/>搜索</button>
   <div className="mlFilters"><label>课程<select aria-label="资源课程" value={filter.course_id} onChange={e=>change({...filter,course_id:e.target.value,page:1})}><option value="">全部课程</option>{courses.map(c=><option key={c.course_id} value={c.course_id}>{c.display_name}</option>)}</select></label><label>标签<input aria-label="资源标签" value={draft.tag} maxLength={100} placeholder="输入标签" onChange={e=>setDraft({...draft,tag:e.target.value})}/></label><label>{filter.kind==='exam'?'考试年份':'出版年份'}<input aria-label="资源年份" type="number" min="1" max="9999" placeholder="不限" value={draft.year} onChange={e=>setDraft({...draft,year:e.target.value})}/></label><button type="submit">应用筛选</button><button type="button" onClick={()=>change({q:'',course_id:'',kind:filter.kind,tag:'',year:'',page:1})}>清除条件</button></div>
  </form><nav className="mlTabs" aria-label="资源类型">{([['textbook','教材'],['exam','试卷']] as const).map(([kind,label])=><button key={kind} aria-pressed={filter.kind===kind} onClick={()=>change({...filter,kind,year:'',page:1})}><StudentIcon name={kind==='textbook'?'library':'file'}/>{label}</button>)}</nav>
  {loading&&<p className="mlState" role="status">正在加载目录…</p>}{error&&<div role="alert" className="mlError">{error}{status===401?<a href="/login">重新登录</a>:<button onClick={()=>setRetry(n=>n+1)}>重试目录</button>}</div>}
  {!loading&&!error&&data&&<><p className="mlCount">共 {data.total} 项可见资料 · 第 {data.page} 页</p><div className="mlGrid">{data.items.map(item=><article key={item.resource_id} className="mlCard"><Cover key={item.resource_id+item.cover_url} item={item}/><div className="mlCardBody"><h2>{item.title}</h2><p>{[item.edition,item.volume].filter(Boolean).join(' · ')||'版次未提供'}</p><p>{item.authors?.join(' / ')||'作者未提供'}</p><p>{item.kind==='exam'?'考试年份':'出版年份'}：{(item.kind==='exam'?item.exam_year:item.publication_year)??'未提供'}{item.page_count!=null&&` · ${item.page_count} 页`}</p><div className="mlTags">{item.tags?.map(tag=><span key={tag}>{tag}</span>)}{(item.role==='primary'||item.role==='supplementary')&&<span>{item.role==='primary'?'主教材':'辅教材'}</span>}</div><p className="mlCompleteness">{item.completeness==='complete'?'文件完整性：完整':item.completeness==='partial'?'文件完整性：部分内容':'文件完整性待核对'}</p><button className="mlRead" disabled={item.availability!=='ready'||!materialAsset(item,'pdf')} onClick={()=>void openPdf(item)}>{item.availability==='restricted'?'访问受限':item.availability!=='ready'?'原件待就绪':!materialAsset(item,'pdf')?'暂无可用 PDF':'阅读 PDF'}<StudentIcon name="arrow"/></button></div></article>)}</div>{!data.items.length&&<div className="mlState">当前条件下暂无可见资料。{filter.page>1&&<button onClick={()=>change({...filter,page:1})}>返回第一页</button>}</div>}<nav className="mlPagination" aria-label="目录分页"><button disabled={filter.page<=1} onClick={()=>change({...filter,page:filter.page-1})}>上一页</button><span>第 {data.page} / {Math.max(1,Math.ceil(data.total/data.page_size))} 页</span><button disabled={data.page*data.page_size>=data.total} onClick={()=>change({...filter,page:filter.page+1})}>下一页</button></nav></>}
  </>}
 </section>;
}
